-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 27 Apr 2017 la 15:23
-- Versiune server: 10.1.21-MariaDB
-- PHP Version: 7.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `characters`
--

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `characters`
--

CREATE TABLE `characters` (
  `ID` int(7) NOT NULL,
  `name` text NOT NULL,
  `details` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Salvarea datelor din tabel `characters`
--

INSERT INTO `characters` (`ID`, `name`, `details`) VALUES
(0, 'linebeck', ''),
(1, 'link', 'The protagonist of The Legend of Zelda series, Link, is the name of various Hylian youths who characteristically wear a green tunic and a pointed cap. He has the pointed ears of the ancient Hylian race. He also has the Triforce symbol on his left hand. Each Link is described on the series\' official website as humble, hard-working and brave, and therefore appropriate to bear the Triforce of Courage. The various Links each have a special title, such as \"Hero of Time\", \"Hero of the Winds\" or \"Hero chosen by the gods\". Link is left-handed, with two exceptions. In the Wii version of Twilight Princess, Link is right-handed due to the \"mirroring\" used to accommodate the right-handed control scheme,[1] which flips the entire game world\'s layout from that of its Nintendo GameCube counterpart. Link is also right-handed in the title Skyward Sword. In the manual for the original game, he is depicted as being right-handed, and in the game itself, Link is seen as ambidextrous as his sword is in the \"down screen side\" whether he is facing left or right . In The Legend of Zelda: Ocarina of Time Master Quest, the game is also mirrored and instead, Link is right-handed.'),
(2, 'zelda', 'Princess Zelda is the princess of Hyrule and guardian of the Triforce of Wisdom. Her name is shared by many of her female ancestors and descendants. While most titles require Link to save Zelda from Ganon, she is sometimes shown to be quite capable in battle, using magical powers and weapons such as Light Arrows to aid Link. With the exception of the CD-i games, she was not playable in the main series until Spirit Tracks, where she becomes a spirit and can possess a Phantom Knight that can be controlled by the player. Zelda also appears under various other aliases and alter egos, including Sheik (in Ocarina of Time) and Tetra (in The Wind Waker and Phantom Hourglass).\r\n\r\n\r\n'),
(3, 'ganondorf', 'Ganondorf (or Ganon in his beast form) is the central villain in the series and serves as the final boss of most games.\r\n\r\nIn the games, Ganondorf is the leader of a race of desert brigands called the Gerudo, and the evil archenemy of Link. His specific motives vary from game to game, but most often they include him kidnapping Princess Zelda and planning to achieve domination of Hyrule, and presumably the world beyond it. To this end, he seeks the Triforce, a magical relic giving the holder ultimate power.\r\n\r\nIn many games, he already possesses or acquires a portion of the Triforce called the Triforce of Power, which gives him great strength but not enough to accomplish his ends, leading him to hunt the remaining Triforce pieces. This story is told during Ocarina of Time, when he uses the child Link, who has gained access to the Master Sword in the Temple of Time, to grab the Triforce. Since Ganondorf\'s heart is not in balance of all three pieces, but only to the Triforce of Power, it breaks in three - Power given to Ganondorf, Courage given to Link (who is then in an unconscious state for 7 years), and Wisdom to Zelda (who has gone into hiding as Sheik). In order to possess all three, he must vanquish the other two. Ocarina of Time splits the timeline in three: if the hero is defeated, if Ganon is sealed in the Earth, and if Ganon is sealed in the Sacred Realm. In the timeline of Ganon being sealed in the Earth, depicted in Twilight Princess, it is revealed that Ganondorf lost his piece before dying.'),
(4, 'agahnim', 'Agahnim is an evil wizard who appears in The Legend of Zelda: A Link to the Past as the initial villain. First appearing in Hyrule during a period of flood, famine and disease, Agahnim assisted the Royal Family by dispelling the multiple plagues and became their trusted advisor for a time, but soon displayed his true colors and seized power for himself. After killing the King of Hyrule and brainwashing the castle soldiers, Agahnim begins using his power to capture the descendants of the Seven Sages and banish them to the Dark World in order to release Ganon from his imprisonment. Link is unable to stop Agahnim in time to save the last of the maidens, Princess Zelda, but he is able to defeat Agahnim by using the Master Sword to reflect the wizard\'s magic onto himself (a tactic that would be used in many later Zelda games).\r\n\r\nAs a last act of defiance, Agahnim escapes to the Dark World and drags Link with him, which begins the second half of the game\'s plot. Near the end, Agahnim meets with Link again on the highest floor of Ganon\'s Tower and is finally slain after another battle, and it is revealed that his body is a vessel for Ganon\'s soul to inhabit (as Ganon admits that Aghanim is his \"alter-ego\").\r\n\r\nIn Link\'s Awakening, Agahnim\'s Shadow was one of the Shadows of Link\'s former foes that attacked Link in the final battle in Koholint Island\'s Wind Fish Egg.'),
(5, 'dark link', 'Dark Link (also known as Shadow Link in Oracle of Ages and Four Swords Adventures) is a recurring boss in the series, and is a doppelgänger of Link. Also known to Zelda as a twisted echo in the Four Swords manga, Dark Link is usually solid black with red eyes but is white with purple hair in the Four Swords Plus manga. In general, Dark Link just copies Link\'s swordplay, but in some games he is able to use Link\'s full arsenal of weapons. He is formed in various ways between the games, though always involving some sort of magical summoning. When he first appears in The Adventure of Link, he is the final boss of the game, and was created by a mysterious wizard as a test for the Triforce of Courage. In Oracle of Ages, Shadow Links are summoned by the sorceress Veran during the final battle. These Shadow Links do not directly attack and quickly die from repeated sword blows, but they mimic Link\'s movements so as to impede his ability to target Veran herself.'),
(6, 'twinrova', 'Kotake and Koume, collectively referred to as the Twinrova Sisters seimajutsushi Tsuinr?ba?, lit. \"Twin Magicians Twinrova\") /?tw?n?ro?v?/, are a pair of Gerudo witches who play an important role in a few games. They are the surrogate mothers of the Gerudo King, Ganondorf, being his more devoted servants. They can brainwash others to serve Ganondorf (they do so to the Sage Nabooru in the Spirit Temple of Ocarina of Time) and merge to form the stronger witch Twinrova. The brooms the sisters use to fly become scepters through which Twinrova channels her power.\r\n\r\nThey portray the same characters in Majora\'s Mask, though they are more benevolent than their Ocarina of Time counterparts. Koume operates a tour-boat service in the Southern Swamp, while Kotake runs a potion store in the same region. At one point, Koume is injured by the Skull Kid in the nearby Lost Woods and requests that Link bring her a red potion from Kotake\'s store to heal her wounds. After saving Koume from the woods and returning the swamp to normal, she will host a shooting game that Link can play and win a Piece of Heart from.'),
(8, 'demise', 'Demon King Demise is the primary antagonist in the The Legend of Zelda: Skyward Sword who was punished by the Goddess Hylia when he attempted to take the Triforce and was trapped within the form of a giant monster known as the Imprisoned. But his sword, which assumes the form of the arrogant Demon Lord Ghirahim, tracks down Hylia\'s reincarnation Zelda so he can use her life force to restore Demise to his true form. Impressed to see a human like Link willing to stand up to him, Demise decides to battle him out of amusement. After Link mortally wounds him and restores Zelda\'s soul to her body, Demise\'s remains are sealed within the Master Sword, but Demise\'s final words speak of a new incarnation of his malice living on, alluding to Ganondorf and the bonds that tie him with Zelda and Link\'s descendants. In Hyrule Warriors, Demise appears in his Imprisoned form before being defeated, with Ghirahim eventually serving Ganondorf while sensing his master\'s presence in him.'),
(9, 'ghirahim', 'Demon Lord Ghirahim is the secondary antagonist in Skyward Sword. He is encountered several times throughout the game, as he relentlessly pursues Zelda in order to revive Demise. Though he appears delicate and acts in a playful, flamboyant manner, Ghirahim is a cruel sadist with a dangerous short-fused temper. He arrogantly toys with Link in their first two battles, then reveals his full power in a final battle prior to Demise\'s release. With his mission accomplished, Ghirahim is revealed to be the spirit of Demise\'s sword, given life for the sole purpose of restoring his master to his original form. He returns to his sword form before being shattered during Demise\'s climactic battle with Link. During the events of Hyrule Warriors, Ghirahim is summoned from the past by Cia to fight for her before becoming a follower of the revived Ganondorf. Ghirahim also appears in Super Smash Bros. for Nintendo 3DS and Wii U as an Assist Trophy.'),
(10, 'zant', 'Usurper King Zant is the secondary antagonist of Twilight Princess, a member of the Twili who willingly offered himself to Ganondorf, whom he saw as a god, so he could have the means to depose Midna and begin an invasion of Hyrule. Though Midna recruits Link to help her collect Fused Shadows so she can regain both her original form and her birthright as the ruler of the Twili, Zant reveals the curse he placed on Midna is Ganondorf\'s after being fatally wounded. Though Zant claims he would be revived while being subsequently destroyed by a furious Midna, Zant\'s death is assured with Ganondorf\'s. The final battle against Zant involves fighting him in the arenas of other bosses and sub-bosses in the game such as Blizzeta, before fighting him in a final sword fight in front of Hyrule castle. During the events of Hyrule Warriors, Zant is summoned from the past by Cia to fight for her before becoming a follower of the revived Ganondorf.'),
(11, 'vaati', 'Vaati, is the main antagonist of The Legend of Zelda: Four Swords, Four Swords Adventures, and The Minish Cap. His most common appearance is a black orb with a single eye, though he was originally a human-shaped being. In Four Swords, Vaati is initially sealed in the \"Four Sword\" weapon, but escapes and captures Princess Zelda, only to be returned to the sword by Link, who is split into four by the sword. In the sequel, Four Swords Adventures, he escapes with Princess Zelda yet again with the help of Ganon, forcing Link to be split up and defeat him. Before the events of The Minish Cap, Vaati was a Picori that became corrupted by the evil in the hearts of mankind. He used the Wishing Cap created by his master, Ezlo, to transform himself into a Hylian sorcerer, and in the game he begins seeking out the power of the Light Force. He eventually becomes his black orb form in this game.\r\n\r\n'),
(12, 'yuga', 'Yuga is a character and one of the two primary antagonists of The Legend of Zelda: A Link Between Worlds. He hunted the descendants of the Seven Sages from Ocarina of Time and A Link to the Past, as well as Princess Zelda, to resurrect Ganon and use his power to rule the worlds of Hyrule and Lorule, and eventually take his place among the gods. He is a sorcerer who has the power to transform himself and others into two-dimensional art. With his magic staff, he can trap people within picture frames, turning them into Lorule paintings.'),
(13, 'majora', 'The primary antagonist in the game, Majora\'s Mask, \"Majora\", inhabits the eponymous \"Majora\'s Mask\"; once used by a nameless tribe for hexing and torture. The mask is primarily seen being worn over the face of \"Skull Kid\", the game\'s secondary antagonist, who is corrupted by Majora\'s influences and uses the mask\'s dark magic to wreak havoc across Termina. During the final boss, two more forms of Majora are shown; Majora\'s Incarnation and Majora\'s Wrath. Both are humanoid creatures, though Majora\'s Wrath has long, whip-like arms. \"Skull Kid\" with Majora\'s Mask also appears as an assist trophy in Super Smash Bros. for Nintendo 3DS and Wii U.'),
(14, 'eponia', 'Epona is Link\'s horse who helps Link in Ocarina of Time, Majora\'s Mask and in Twilight Princess. She comes to Link\'s aid when called by her special song, which he plays on the ocarina in Ocarina of Time and Majora\'s Mask, and on a blade of grass (called Horse Grass) in Twilight Princess. In The Legend of Zelda: Oracle of Seasons and Oracle of Ages, the horse that Link rides in the title screen is possibly either Epona or a different horse.'),
(15, 'fi', 'Fi is a female humanoid representation of the Goddess Sword, which later evolves into the Master Sword, in Skyward Sword. Fi serves as Link\'s companion and assists him throughout the game, though she has a logical mindset and grows to understand her master and others. In the end, after Demise is sealed within the Master Sword, Fi reveals her last order from the goddess is to let Link put her into an endless sleep within the weapon, which he does after encouragement from Fi and Zelda. Fi appears as a playable character in Hyrule Warriors.'),
(16, 'golden goddess', 'The three Golden Goddesses (Din, Farore and Nayru) are responsible for the creation of Hyrule, as well as the creation of the Triforce, which houses a fraction of their divine power. Din is the Goddess of Power, associated with the color red and the elements of earth and fire; Farore is the Goddess of Courage, associated with the color green and the elements of wind and forest; and Nayru is the Goddess of Wisdom, associated with the color blue and the elements of water and time. Each Goddess is also associated with a fragment of the Triforce—Din with the Triforce of Power, Farore with the Triforce of Courage, and Nayru with the Triforce of Wisdom. Each Goddess has a spell that Link may acquire from a Great Fairy—Din\'s Fire, Farore\'s Wind, and Nayru\'s Love. These three spells are used by Princess Zelda in Super Smash Bros. Melee and Super Smash Bros. Brawl. Statues appear in The Wind Waker, depicting the three Goddesses. These statues are arranged in a triangle shape.'),
(17, 'great deku tree', 'The Great Deku Tree is considered the \"Father of the Forest\"; he first appears in Ocarina of Time, where he is charged with watching over the Kokiri, a childlike race of forest spirits that live in the Kokiri Forest. He is an ancient, exceptionally large tree, with a humanoid face and big mustache.\r\n\r\nWhen Ocarina of Time begins, the Great Deku Tree is suffering from a curse cast upon him by Ganondorf in an effort to gain the Spiritual Stone of the Forest, which is in the Deku Tree\'s possession. Knowing Link\'s destiny, the Deku Tree sends Navi the fairy to retrieve the boy, who is living among the Kokiri as one of them. He asks Link to destroy the cause of the curse, the game\'s first boss, called Queen Gohma, within him. Although Link defeats Queen Gohma, the Deku Tree was doomed before Link had begun; before he dies, the Deku Tree gives Link the Kokiri\'s Emerald and tells him to seek Princess Zelda at Hyrule Castle. After adult Link completes the Forest Temple and returns to the site of the Deku Tree, he discovers a little sprout, which grows into the Deku Sprout. The sprout tells Link the truth about his past, and reveals that Link is not a Kokiri, but a Hylian entrusted to the Deku Tree by his mother, who died soon after.'),
(18, 'groose', 'Groose is a bully from the Knights\' Academy in Skyward Sword, initially jealous of Link\'s relationship with Zelda, and often acts in a hostile manner towards Link, which is shown to be a constant source of exasperation for Zelda. However, following Link to Hyrule, Groose finds himself over his head upon learning he is not the hero and is forced to accept it. Becoming more caring, Groose begins acting more noble from building a catapult called \"The Groosenator\" to aid Link in halting The Imprisoned from escaping the pit of the Sealed Grounds and reaching the Sealed Temple, and begins to look after the elderly overseer of the Sealed Grounds whom he calls \"Grannie\". He is playable during the last two battles with the Imprisoned. In these circumstances, the player can move the Groosenator around the edge of the Sealed Grounds and then fire giant bombs at it.'),
(19, 'happy masks salesman', 'The Happy Mask Salesman is a mysterious man who specialises in masks, which Link can use for different purposes. He is almost always happy, with few exceptions. He first appears in Ocarina of Time. He is found in his Happy Mask Shop located in Hyrule Castle town during Link\'s childhood. Here, Link can borrow masks to sell to people around Hyrule. If Link returns without enough Rupees to repay the Happy Mask Salesman, he will become enraged and kick Link out of the shop. Once Link sells all the masks, he may borrow any of them, as well as a few extras, which are used merely for humorous purposes. The exception is the Mask of Truth, which Link can use to talk to Gossip Stones.'),
(20, 'impa', 'Impa is a caretaker to Princess Zelda. There are many incarnations of the character named Impa throughout the Zelda series, some being of the ninja-like Sheikah, just as there are multiple incarnations of Link and Zelda. As with Link and Zelda, all incarnations of Impa share certain personality traits.\r\n\r\nThe original Impa (appearing in The Legend of Zelda and The Adventure of Link instruction manuals, but not in the actual games) is portrayed as an old woman who calls for Link to save Zelda from Ganon and his henchmen. The Impa from The Legend of Zelda is also supposed to be the same Impa who appears in the Philips spin-off Zelda: Wand of Gamelon. The voice of Impa in Zelda: The Wand of Gamelon is Eve Karpf.\r\n\r\nThe Impa of Ocarina of Time is a Sheikah who is both Zelda\'s bodyguard and a descendent of the tribe that founded Kakariko Village. It is later revealed that she is in fact the Sage of Shadow, one of the Seven Sages. An overweight version of Impa is a main character in Oracle of Seasons and Oracle of Ages, the latter having her briefly possessed by Veran.'),
(21, 'kaepora gaebora', 'Kaepora Gaebora is a wise owl who guides Link throughout various games in the series. One of the Gossip Stones in Ocarina of Time (found in the Sacred Forest Meadow) says he is the reincarnation of an ancient sage. This sage is Rauru, the Sage of Light in the Temple of Light. Another Gossip Stone in the same area tells Link that Kaepora Gaebora \"may look big and heavy, but its character is rather lighthearted.\" Despite him guiding Link throughout his childhood in Ocarina of Time, he is not encountered while an adult except near the end. He is seen flying over Lon Lon Ranch when Link learns Epona\'s Song and in shadows when Link learns the Requiem of Spirit, but makes no other appearance until Link completes the child half of the Spirit Temple; after that, he is seen flying away during the credits. Kaepora Gaebora remarks, \"Even I thought that the tales of a boy who traveled back and forth through time were merely a legend,\" when Link meets him for the last time. He also tells Link, \"The future of all the people in Hyrule is on your shoulders. Maybe it\'s not my time anymore.\" He is notorious for asking Link if he would like to hear what he said again at the end of each conversation. The default choice is always \"Yes\".'),
(22, 'king daphnes', 'King Daphnes Nohansen Hyrule is the last king of Hyrule in The Wind Waker. To meet with Link, he remotely operates the King of Red Lions, a talking boat, using magic. By the end of the game, the King wishes to the Triforce for Hyrule to be destroyed, and stays with the kingdom as it is flooded.\r\n\r\nOther Kings of Hyrule appear or are mentioned in the series. In A Link to the Past, the king only appears during the intro and ending credits. In Ocarina of Time, it is stated that Princess Zelda\'s father is the king and Ganondorf is seen approaching and kneeling to him when Link and Princess Zelda first meet, although the king himself is never shown and his ultimate fate is never revealed. In The Minish Cap, the current ruler, King Daltus, is a major character during the game, and his ancestor King Gustaf appears to help Link enter the fifth dungeon. King Daphnes appears as a playable character in Hyrule Warriors Legends, with the ability to transform into the King of Red Lions in battle.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `characters`
--
ALTER TABLE `characters`
  ADD PRIMARY KEY (`ID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
